[package]
name = "switchpro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bluez-async = "0.5.5"
tokio = { version = "1.18.0", features = ["full"] }
tokio-stream = "0.1.8"
